# .github/workflows/backend-ci.yml
name: Backend CI

on:
  push:
    paths:
      - 'mapquester_backend/**'
    branches: [ main, dev ]
  pull_request:
    paths:
      - 'mapquester_backend/**'
    branches: [ main, dev ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mapquester_backend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black

    - name: Check Code Style (Black)
      run: |
        black . --check
        
    - name: Check Code Quality (Flake8)
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-line-length=88 --statistics

  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mapquester_backend

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: mapquester_user       # Matching your DB_USER
          POSTGRES_PASSWORD: your_secure_password  # Matching your DB_PASSWORD
          POSTGRES_DB: mapquester              # Matching your DB_NAME
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: mapquester.settings
        SECRET_KEY: your_secret_key_here
        DEBUG: True
        ALLOWED_HOSTS: localhost,127.0.0.1
        DB_ENGINE: django.db.backends.postgresql
        DB_NAME: mapquester
        DB_USER: mapquester_user
        DB_PASSWORD: your_secure_password
        DB_HOST: localhost
        DB_PORT: 5432
        TIME_ZONE: UTC
        LANGUAGE_CODE: en-us
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python manage.py test